# use_thin_strokes = false

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.cursor]
cursor = "#c7c7c7"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#101421"
foreground = "#fffbf6"

[env]
TERM = "xterm-256color"

[font]
size = 14.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0004"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\t"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = """

"""
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\r"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0014"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0019"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001A"
key = "Z"
mods = "Command"

[general]
live_config_reload = true

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
# startup_mode = "Fullscreen"

[keyboard]
